"use client";

import { useMemo, useState } from "react";

import type { Mission } from "@/types/mission";
import { resolvePracticalModule } from "@/lib/practicalConfig";

type ReportBuilderProps = {
  mission: Mission;
};

export default function ReportBuilder({ mission }: ReportBuilderProps) {
  const module = resolvePracticalModule(mission.type);
  const isSocMission = [
    "SOC_ALERT",
    "SIEM",
    "PHISHING",
    "MALWARE",
    "INCIDENT_RESPONSE",
    "THREAT_HUNT"
  ].includes(mission.type);

  const [summary, setSummary] = useState(mission.scenario ?? mission.description);
  const [evidence, setEvidence] = useState("");
  const [timeline, setTimeline] = useState("");
  const [recommendation, setRecommendation] = useState("");
  const [finding, setFinding] = useState("");
  const [severity, setSeverity] = useState("High");
  const [impact, setImpact] = useState("");
  const [fix, setFix] = useState("");

  const markdown = useMemo(() => {
    if (isSocMission) {
      return `# SOC Incident Report — ${mission.title}

## Incident Summary
${summary}

## Evidence
${evidence || "_Document artifacts collected during investigation._"}

## Timeline
${timeline || "_Reconstruct events in chronological order._"}

## Recommendation
${recommendation || "_Remediation and monitoring steps._"}

---
_Generated by Nexus Report Builder_
`;
    }
    return `# Penetration Test Finding — ${mission.title}

## Finding
${finding || summary}

## Severity
${severity}

## Impact
${impact || "_Business and technical impact._"}

## Proof of Concept
${evidence || "_Steps to reproduce in lab environment._"}

## Remediation
${fix || recommendation || "_Recommended fix._"}

---
_Generated by Nexus Report Builder_
`;
  }, [mission.title, summary, evidence, timeline, recommendation, finding, severity, impact, fix, isSocMission, module]);

  function exportMarkdown() {
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${mission.slug}-report.md`;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  return (
    <section className="rounded-xl border border-blue-900/50 bg-black/40 p-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h3 className="text-lg text-blue-300">Report Builder</h3>
        <button
          type="button"
          onClick={exportMarkdown}
          className="border border-blue-600 px-4 py-2 text-sm text-blue-400 hover:bg-blue-950"
        >
          Export Markdown
        </button>
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-2">
        <div className="space-y-3">
          <textarea
            value={summary}
            onChange={event => setSummary(event.target.value)}
            placeholder="Summary / finding"
            className="h-24 w-full border border-green-900/40 bg-black p-3 text-sm text-gray-300 outline-none"
          />
          <textarea
            value={evidence}
            onChange={event => setEvidence(event.target.value)}
            placeholder="Evidence / proof"
            className="h-24 w-full border border-green-900/40 bg-black p-3 text-sm text-gray-300 outline-none"
          />
          {!isSocMission && (
            <>
              <select
                value={severity}
                onChange={event => setSeverity(event.target.value)}
                className="w-full border border-green-900/40 bg-black p-2 text-sm text-gray-300"
              >
                {["Critical", "High", "Medium", "Low", "Info"].map(level => (
                  <option key={level} value={level}>
                    {level}
                  </option>
                ))}
              </select>
              <textarea
                value={impact}
                onChange={event => setImpact(event.target.value)}
                placeholder="Impact"
                className="h-20 w-full border border-green-900/40 bg-black p-3 text-sm text-gray-300 outline-none"
              />
            </>
          )}
          {isSocMission && (
            <textarea
              value={timeline}
              onChange={event => setTimeline(event.target.value)}
              placeholder="Timeline"
              className="h-20 w-full border border-green-900/40 bg-black p-3 text-sm text-gray-300 outline-none"
            />
          )}
          <textarea
            value={recommendation || fix}
            onChange={event => {
              setRecommendation(event.target.value);
              setFix(event.target.value);
            }}
            placeholder="Recommendation / fix"
            className="h-20 w-full border border-green-900/40 bg-black p-3 text-sm text-gray-300 outline-none"
          />
        </div>
        <pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded border border-green-900/30 bg-black/60 p-4 text-xs text-green-300">
          {markdown}
        </pre>
      </div>
    </section>
  );
}
